// Generates dist/sw.js with the hashed build assets precached, so the app
// loads fully offline after the first visit. Run after `vite build`.
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const dist = 'dist';
if (!existsSync(join(dist, 'index.html'))) {
  console.error('dist/index.html not found — run `vite build` first.');
  process.exit(1);
}

const indexHtml = readFileSync(join(dist, 'index.html'), 'utf8');
const assets = [...indexHtml.matchAll(/(?:src|href)="(\/assets\/[^"]+)"/g)].map((m) => m[1]);
const icons = existsSync(join(dist, 'icons'))
  ? readdirSync(join(dist, 'icons'))
      .filter((f) => f.endsWith('.png'))
      .map((f) => `/icons/${f}`)
  : [];
const core = ['/', '/index.html', '/manifest.webmanifest', ...icons, ...assets];

const sw = `/* Flex POS — service worker (offline support) — generated by scripts/gen-sw.mjs */
const CACHE = 'flex-pos-v1';
const CORE = ${JSON.stringify(core, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(CORE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: network first, fall back to cached shell (offline).
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => cache.put('/index.html', copy));
          return res;
        })
        .catch(() => caches.match('/index.html'))
    );
    return;
  }

  // Hashed build assets: cache first (instant offline), refresh in background.
  event.respondWith(
    caches.match(req).then((cached) => {
      const network = fetch(req)
        .then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((cache) => cache.put(req, copy));
          }
          return res;
        })
        .catch(() => cached);
      return cached || network;
    })
  );
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
console.log(`gen-sw: precached ${core.length} files (${assets.length} hashed assets) -> dist/sw.js`);
